In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [6]:
type(a)

numpy.ndarray

In [7]:
print(np.__version__)

2.4.4


In [10]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[3:6])

[4 5 6]


In [11]:
print(arr[2]+arr[3])

7


In [16]:
arr=np.array(["a","b","c"])
print(type(arr))
arr

<class 'numpy.ndarray'>


array(['a', 'b', 'c'], dtype='<U1')

In [19]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [20]:
print(arr.shape)

(2, 4)


In [21]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


In [24]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [34]:
newarr=arr.reshape(4,3)

In [35]:
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [36]:
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [38]:
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [40]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
arr=np.concatenate((arr1,arr2))
print(arr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [41]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[10,11,12],[13,14,15],[16,17,18]])
arr=np.concatenate((arr1,arr2))
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [45]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.stack((arr1,arr2),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [46]:
arr=np.array([10,14,93,41,8,7])
x=np.where(arr%2==0)
print(x)

(array([0, 1, 4]),)


In [47]:
arr=np.array([10,14,93,41,8,7])
x=np.where(arr%2==1)
print(x)

(array([2, 3, 5]),)


In [48]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [72]:
a=np.arange(81)
np.array(a)[::-1]

array([80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64,
       63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47,
       46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30,
       29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [58]:
arr=np.array([6,70,15,9])
np.sort(arr)

array([ 6,  9, 15, 70])

In [69]:
arr=np.array([6,70,15,9,20])
np.sort(arr)[::-1]

array([70, 20, 15,  9,  6])

In [77]:
da=np.array(sorted(arr,reverse=True))
print(da)

[70 20 15  9  6]


In [78]:
arr=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=arr[x]
print(newarr)

[41 43]


In [79]:
import numpy as np
arr=np.array([41,42,43,44])
x=[]
for element in arr:
    if element in arr:
        x.append(True)
    else:
        x.append(False)

newarr=arr[x]
print(newarr)

[41 42 43 44]
